window.KPC_CONFIG = {
  SUPABASE_URL: 'https://YOUR-PROJECT.supabase.co',
  SUPABASE_PUBLISHABLE_KEY: 'YOUR_SUPABASE_PUBLISHABLE_KEY',
  PRICE: 227000,
  BANK_NAME: 'BCA',
  BANK_ACCOUNT: '1234567890',
  BANK_HOLDER: 'PT KPC JERSEY INDONESIA'
};
